MNIST is the "Hello World" of computer vision. 
In this notebook, let's classify the MNIST digits with deap learning CNN, with tf.Keras part of the TensorFlow core API.

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

In [2]:
import tensorflow as tf
import pandas as pd
from tensorflow import keras
print(tf.__version__)

1.11.0-rc1


**Load train dataset**

In [3]:
train = pd.read_csv("../input/train.csv")
print("train dataset shape is ", train.shape)
train.head()


train dataset shape is  (42000, 785)


label  pixel0  pixel1    ...     pixel781  pixel782  pixel783
0      1       0       0    ...            0         0         0
1      0       0       0    ...            0         0         0
2      1       0       0    ...            0         0         0
3      4       0       0    ...            0         0         0
4      0       0       0    ...            0         0         0

[5 rows x 785 columns]

**Train dataset **- split into image pixel data and labels

In [4]:
# All pixel values - all rows and column 1 (pixel0) to column 785 (pixel 783)
x_train = (train.iloc[:,1:].values).astype('float32') 
# Take a look at x_train
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [5]:
# Labels - all rows and column 0
y_train = (train.iloc[:,0].values).astype('int32') 

# Take a look at y_train
y_train

array([1, 0, 1, ..., 7, 6, 9], dtype=int32)

**Load test dataset**

In [6]:
test = pd.read_csv("../input/test.csv")
print("test dataset shape is ", test.shape)
test.head()

test dataset shape is  (28000, 784)


pixel0  pixel1  pixel2    ...     pixel781  pixel782  pixel783
0       0       0       0    ...            0         0         0
1       0       0       0    ...            0         0         0
2       0       0       0    ...            0         0         0
3       0       0       0    ...            0         0         0
4       0       0       0    ...            0         0         0

[5 rows x 784 columns]

In [7]:
x_test = test.values.astype('float32')

In [8]:
x_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

### Preprocess data

In [9]:
num_classes = 10

# Normalize the input data
x_train = x_train.astype('float32') / 255
x_test = x_test.astype('float32') / 255

# Reshape input data from (28, 28) to (28, 28, 1)
w, h = 28, 28
x_train = x_train.reshape(-1, w, h, 1)
x_test = x_test.reshape(-1, w, h, 1)

# One-hot encode the labels
y_train = keras.utils.to_categorical(y_train, num_classes)

# Take a look at the dataset shape after conversion with keras.utils.to_categorical
print("x_train shape:", x_train.shape, "y_train shape:", y_train.shape)

x_train shape: (42000, 28, 28, 1) y_train shape: (42000, 10)


### Define the model architecture

In [10]:
model = keras.Sequential()

# Must define the input shape in the first layer of the neural network
model.add(keras.layers.Conv2D(filters=32, kernel_size=3, padding='same', activation='relu', input_shape=(28,28,1))) 
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.MaxPooling2D(pool_size=2))
model.add(keras.layers.Dropout(0.3))

model.add(keras.layers.Conv2D(filters=64, kernel_size=3, padding='same', activation='relu'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.MaxPooling2D(pool_size=2))
model.add(keras.layers.Dropout(0.3))

model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(128, activation='relu'))
model.add(keras.layers.Dropout(0.5))
model.add(keras.layers.Dense(10, activation='softmax'))

# Take a look at the model summary
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 28, 28, 32)        320       
_________________________________________________________________
batch_normalization (BatchNo (None, 28, 28, 32)        128       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 32)        0         
_________________________________________________________________
dropout (Dropout)            (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 14, 14, 64)        18496     
_________________________________________________________________
batch_normalization_1 (Batch (None, 14, 14, 64)        256       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 7, 7, 64)          0         
__________

**Model Compilation**

In [11]:
model.compile(loss=keras.losses.categorical_crossentropy,
             optimizer=keras.optimizers.Adam(),
             metrics=['accuracy'])

**Fitting data into Model**

In [14]:
model.fit(x_train,
         y_train,
         batch_size=64,
         epochs=40)

Epoch 1/40
42000/42000 [==============================] - 8s 186us/step - loss: 0.0436 - acc: 0.9865
Epoch 2/40
42000/42000 [==============================] - 8s 179us/step - loss: 0.0369 - acc: 0.9885
Epoch 3/40
42000/42000 [==============================] - 7s 178us/step - loss: 0.0396 - acc: 0.9882
Epoch 4/40
42000/42000 [==============================] - 7s 178us/step - loss: 0.0392 - acc: 0.9879
Epoch 5/40
42000/42000 [==============================] - 7s 177us/step - loss: 0.0406 - acc: 0.9880
Epoch 6/40
42000/42000 [==============================] - 7s 177us/step - loss: 0.0343 - acc: 0.9895
Epoch 7/40
42000/42000 [==============================] - 7s 177us/step - loss: 0.0352 - acc: 0.9897
Epoch 8/40
42000/42000 [==============================] - 7s 177us/step - loss: 0.0339 - acc: 0.9893
Epoch 9/40
42000/42000 [==============================] - 7s 177us/step - loss: 0.0325 - acc: 0.9899
Epoch 10/40
42000/42000 [==============================] - 7s 175us/step - loss: 0.0320 - a

In [15]:
predictions = model.predict_classes(x_test, verbose=0)

submissions=pd.DataFrame({"ImageId": list(range(1,len(predictions)+1)),
                         "Label": predictions})
submissions.to_csv("mnist_digi_recog.csv", index=False, header=True)